spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ebilag
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: HikariCP

---

Spring:
  flyway:
    enabled: true
    locations: classpath:/db/migration
    clean-disabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

# Logging configuration
logging:
  level:
    org:
      springframework:
        web: DEBUG
